[workspace]
members = [
  "crates/*",
  "crates/optix/examples/ex*",
  "crates/optix/examples/ex*/device",
  "xtask",
  "examples/optix/*"
]

exclude = [
    "crates/optix/examples/common"
]

[profile.dev.package.rustc_codegen_nvvm]
opt-level = 3
